[project]
name = 'Genealogix'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Genealogix]
path = 'contracts/Genealogix.clar'
clarity_version = 3
epoch = 3.1
[contracts.MedicalHistory]
path = 'contracts/MedicalHistory.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
